package commons;

public class Constantes {

    public static String YOURCOMPANY_COMPANY_BANK      = "YOURCOMPANY_COMPANY_BANK";
    public static String YOURCOMPANY_COMPANY_BIC       = "YOURCOMPANY_COMPANY_BIC";
    public static String YOURCOMPANY_COMPANY_CITY      = "YOURCOMPANY_COMPANY_CITY";
    public static String YOURCOMPANY_COMPANY_COUNTRY   = "YOURCOMPANY_COMPANY_COUNTRY";
    public static String YOURCOMPANY_COMPANY_EMAIL     = "YOURCOMPANY_COMPANY_EMAIL";
    public static String YOURCOMPANY_COMPANY_FAX       = "YOURCOMPANY_COMPANY_FAX";
    public static String YOURCOMPANY_COMPANY_IBAN      = "YOURCOMPANY_COMPANY_IBAN";
    public static String YOURCOMPANY_COMPANY_NAME      = "YOURCOMPANY_COMPANY_NAME";
    public static String YOURCOMPANY_COMPANY_OWNER     = "YOURCOMPANY_COMPANY_OWNER";
    public static String YOURCOMPANY_COMPANY_STREET    = "YOURCOMPANY_COMPANY_STREET";
    public static String YOURCOMPANY_COMPANY_TAXOFFICE = "YOURCOMPANY_COMPANY_TAXOFFICE";
    public static String YOURCOMPANY_COMPANY_TEL       = "YOURCOMPANY_COMPANY_TEL";
    public static String YOURCOMPANY_COMPANY_VATNR     = "YOURCOMPANY_COMPANY_VATNR";
    public static String YOURCOMPANY_COMPANY_WEBSITE   = "YOURCOMPANY_COMPANY_WEBSITE";
    public static String YOURCOMPANY_COMPANY_ZIP       = "YOURCOMPANY_COMPANY_ZIP";


    public static String NOMBRE_ARCHIVO_TXT = "ticket.txt";
    public static String NOMBRE_ARCHIVO_PDF = "ticket.pdf";
    public static String NOMBRE_IMPRESORA = "BIXOLON SRP-270";
}
